ExpenseTracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tracker.urls', namespace='tracker')),
]

tracker/urls.py
from django.urls import path
from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='index'),
    path('budget/', views.post_budget, name='post_budget'),
    path('expense-list/', views.list_expense, name='list_expense'),
    path('expense/', views.post_expense, name='post_expense'),
        
]

tracker/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField()
    help_text = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='expense')
    title = models.CharField(max_length=100)    
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='order')
    date = models.DateField(default = timezone.now)
    amount = models.DecimalField(max_digits=6, decimal_places=2, db_index=True)
    deductible = models.BooleanField(default=False)
    comments = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class Budget(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='budget')
    week = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    month = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    annual = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id} - {self.user.username} (#{self.user.id})'

tracker/forms.py
from django import forms
from . import models

##
# Add Bootstrap Class
##
class BootstrapModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BootstrapModelForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control form-control-lg'
            })

class BootstrapForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(BootstrapForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control form-control-lg'
            })
            
class BudgetForm(forms.Form):
    budget_amount = forms.IntegerField()
    budget_periodic = forms.IntegerField(max_value=2)

class ExpenseForm(forms.Form):
    expense_form_title = forms.CharField()
    expense_form_category = forms.CharField()
    expense_form_deductible = forms.BooleanField(initial=False)
    expense_form_date = forms.DateField()
    expense_form_amount = forms.DecimalField()
    expense_form_comment = forms.CharField(empty_value=' ')

tracker/views.py
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.core import serializers
from django.db.models import Avg, Count
from datetime import datetime
from .models import Budget, Expense, Category
from .forms import BudgetForm, ExpenseForm

def index(request):
    return render(request, 'index.html')

@require_POST
def post_budget(request):
    budget, _ = Budget.objects.get_or_create(user=request.user)
    form = BudgetForm(request.POST)  
    
    if form.is_valid(): 
        periodic = form.cleaned_data['budget_periodic']
        amount = abs(form.cleaned_data['budget_amount'])

        if periodic == 0: #week
            budget.week = amount
            budget.month = round((30/7)*amount,2)
            budget.annual = 52*amount
        elif periodic == 1: #month
            budget.week = round((7/30)*amount, 2)
            budget.month = amount
            budget.annual = 52*amount
        elif periodic == 2: #year
            budget.week = round((7/30)*amount/52, 2)
            budget.month = round(amount/12, 2)
            budget.annual = amount
        else:
            return HttpResponse("{'message':'Unable to save'}", content_type='application/json')
    
        budget.save() 
        
    #else:        
        #return JsonResponse(form.errors, safe=False, status=200)
    
    return HttpResponse(serializers.serialize("json", [budget]), content_type='application/json')

@require_POST
def list_expense(request):
    current_year = datetime.now().year
    expense = Expense.objects.filter(user=request.user).filter(date__year=current_year)
    if expense.exists() and expense.count():
        return HttpResponse(serializers.serialize("json", list(expense,)), content_type='application/json')
    else:
        return HttpResponse('{"message":"Empty Object"}', content_type='application/json')    
    
@require_POST
def post_expense(request):
    form = ExpenseForm(request.POST)
    print(form.data)
    
    if form.is_valid():
        cd = form.cleaned_data
        expense = Expense(user=request.user)
        cat = Category.objects.get(title=cd['expense_form_category'] )
        expense.title = cd['expense_form_title']    
        expense.category = cat
        expense.date = cd['expense_form_date']
        expense.amount = cd['expense_form_amount']
        expense.deductible = cd['expense_form_deductible']
        expense.comment = cd['expense_form_comment']
        expense.save()
        return HttpResponse(serializers.serialize("json", [expense]), content_type='application/json')
    else:
        return JsonResponse(form.errors, safe=False, status=200)
    #return HttpResponse('{"message":"Empty Object"}', content_type='application/json')   

tracker/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href='{% static "vendor/fontawesome-free/css/all.min.css" %}' rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href='{% static "css/sb-admin-2.min.css" %}' rel="stylesheet">
</head>
<body id="page-top">
    
    {% block content %} {% endblock %}

<!-- Bootstrap core JavaScript-->
<script src='{% static "vendor/jquery/jquery.min.js" %}'></script>
<script src='{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}'></script>

<!-- Core plugin JavaScript-->
<script src='{% static "vendor/jquery-easing/jquery.easing.min.js" %}'></script>

<!-- Custom scripts for all pages-->
<script src='{% static "js/sb-admin-2.min.js" %}'></script>

<!-- Page level plugins -->
<script src='{% static "vendor/chart.js/Chart.min.js" %}'></script>

<!-- Page level custom scripts -->
<script src='{% static "js/demo/chart-area-demo.js" %}'></script>
<script src='{% static "js/demo/chart-pie-demo.js" %}'></script>
{% block js %}{% endblock %}
</body>
</html>

tracker/templates/includes/budget_form.html
<form action='{% url "tracker:post_budget" %}' method="post" id="budget_form">
    <div class="input-group mb-3">
        <span class="input-group-text">$</span>
        <input type="number" class="form-control" aria-label="Amount (to the nearest dollar)" id="budget_amount" name="budget_amount" max="999999" required>
        <span class="input-group-text">.00</span>
    </div>
    <div class="form-check mx-2">
        <input class="form-check-input" type="radio" id="budget_weekly" name="budget_periodic" value=0 checked>
        <label class="form-check-label" for="budget_weekly">Weekly</label>
    <hr>
        <input class="form-check-input" type="radio" id="budget_monthly" name="budget_periodic" value=1 >
        <label class="form-check-label" for="budget_monthly">Monthly</label>
    <hr>
        <input class="form-check-input" type="radio" id="budget_annually" name="budget_periodic" value=2 >
        <label class="form-check-label" for="budget_annually">Annually</label>
    </div>
    {% csrf_token %}
    <br>
    <div class="col-auto">        
        <button type="submit" class="btn btn-primary form-control" id="budget_submit">Save</button>
    </div>
</form>

tracker/templates/includes/expense_form.html
<form action='{% url "tracker:post_expense" %}' method="post" id="expense_form">
    
    <div class="input-group">
        <span class="input-group-text">Title</span>
        <input type="text" aria-label="Expense Form Title" class="form-control" id="expense_form_title" name="expense_form_title" required>
    </div>

    <div class="input-group">
        <span class="input-group-text">Amount $</span>
        <input type="number" class="form-control" aria-label="Amount" step="0.01" id="expense_form_amount" name="expense_form_amount" max="999999" required>
    </div>
    <div class="input-group">
        <label class="input-group-text form-control" for="expense_form_category">Category</label>
        <select class="form-select" id="expense_form_category" name="expense_form_category">
          <option selected>Choose...</option>
          {% for cat in categories %}
            <option selected>{{ cat }}</option>
          {% endfor %}
        </select>
    </div>
    <br>
    <div class="input-group" data-provide="datepicker">
        <span class="input-group-text">Date</span>
        <input type="date" class="form-control" value="{% now 'Y\-m\-d' %}" id="expense_form_date" name="expense_form_date">
    </div>
    <br>    
    <div class="input-group">
        <label class="input-group-text form-control" for="expense_form_deductible">Deductible</label>
        <select class="form-select" id="expense_form_deductible" name="expense_form_deductible">
          <option value=0 selected="selected" selected>No</option>
          <option value=1>Yes</option>
        </select>
    </div>
    <br>
    <div class="mx-2">
        <label for="expense_form_comment" class="form-label mb-1">Comments</label>
        <textarea class="form-control" id="expense_form_comment" name="expense_form_comment" rows="3"></textarea>
    </div>

    {% csrf_token %}
    <br>
    <div class="col-auto">        
        <button type="submit" class="btn btn-primary form-control" id="expense_submit">Save</button>
    </div>
</form>

tracker/templates/includes/expense_widget.html
{% load tracker_tags %}
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-{{ color }} shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-{{ color }} text-uppercase mb-1">{{ budget_title }}</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800" id="{{ budget_name }}">${{ budget }}</div> 
                    <hr><div class="text-xs font-weight-bold text-{{ color }} text-uppercase mb-1" id="{{ expense_name }}_title">{{ expense_title }} <br>({{ span }})</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800" id="{{ expense_name }}_holder">
                        <div class="h5 mb-0 font-weight-bold text-gray-800" id="{{ expense_name }}">
    
                            ${{ sum | money }}<sup> total</sup><br>
                            ${{ avg | money }}<sup> avg</sup><br>
                            <small>{{ count }} transactions</small> 
                        
                        </div>
                    </div>                                        
                </div>
                <div class="col-auto">
                    <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>

tracker/templates/partials/_footer.html
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Expense Tracker {% now 'Y' %}</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

tracker/templates/partials/_sidebar.html
{% load static %}
{% load tracker_tags %}
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href='{% url "tracker:index" %}'>
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-fw fa-tachometer-alt"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Expense Tracker</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href='{% url "tracker:index" %}'>
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Basic Settings
    </div>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseExpense"
            aria-expanded="true" aria-controls="collapseExpense">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Expenses</span>
        </a>
        <div id="collapseExpense" class="collapse" aria-labelledby="headingExpense"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Add Expenses</h6>
                {% get_expense_form %}
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBudget"
            aria-expanded="true" aria-controls="collapseBudget">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Budget</span>
        </a>
        <div id="collapseBudget" class="collapse" aria-labelledby="headingBudget"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Set Budget</h6>
                {% include 'includes/budget_form.html' %}
            </div>
        </div>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Reports</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Reports:</h6>
                <a class="collapse-item" href='{% url "tracker:index" %}'>Expense Report</a>
                <a class="collapse-item" href='{% url "tracker:index" %}'>Spendings Report</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-cog"></i>
            <span>Settings</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Settings:</h6>
                <a class="collapse-item" href="{% url "tracker:index" %}">General</a>                
                <a class="collapse-item" href="{% url "tracker:index" %}">Graphs</a>
                <a class="collapse-item" href="{% url "tracker:index" %}">Charts</a>
                <a class="collapse-item" href="{% url "tracker:index" %}">Colors Scheme</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Shortcuts
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
            aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">User:</h6>
                <a class="collapse-item" href='{% url "tracker:index" %}'>Login</a>
                <a class="collapse-item" href='{% url "tracker:index" %}'>Register</a>
                <a class="collapse-item" href='{% url "tracker:index" %}'>Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Admin:</h6>
                <a class="collapse-item" href='{% url "admin:index" %}'>Admin Page</a>
                
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href='{% url "tracker:index" %}'>
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href='{% url "tracker:index" %}'>
            <i class="fas fa-fw fa-table"></i>
            <span>Graphs</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    <!-- Sidebar Message -->
    <!--
    <div class="sidebar-card d-none d-lg-flex">
        <img class="sidebar-card-illustration mb-2" src='{% static "img/undraw_rocket.svg" %}' alt="...">
        <p class="text-center mb-2"><strong>Quick </strong> update!</p>
        <a class="btn btn-success btn-sm" href="">Add Expense</a>
    </div>
    -->

</ul>
<!-- End of Sidebar -->

tracker/templates/partials/_topnav.html
{% load static %}

<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-dark topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
 
<!-- Topbar Search -->
<form
class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
<div class="input-group">
    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
        aria-label="Search" aria-describedby="basic-addon2">
    <div class="input-group-append">
        <button class="btn btn-primary" type="button">
            <i class="fas fa-search fa-sm"></i>
        </button>
    </div>
</div>
</form>

<!-- Topbar Navbar -->
<ul class="navbar-nav ml-auto">

    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-search fa-fw"></i>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
            aria-labelledby="searchDropdown">
            <form class="form-inline mr-auto w-100 navbar-search">
                <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small"
                        placeholder="Search for..." aria-label="Search"
                        aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </li>

    <!-- Nav Item - Alerts -->
    <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell fa-fw"></i>
            <!-- Counter - Alerts -->
            <span class="badge badge-danger badge-counter">3+</span>
        </a>
        <!-- Dropdown - Alerts -->
        <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
            aria-labelledby="alertsDropdown">
            <h6 class="dropdown-header">
                Alerts Center
            </h6>
            <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="mr-3">
                    <div class="icon-circle bg-primary">
                        <i class="fas fa-file-alt text-white"></i>
                    </div>
                </div>
                <div>
                    <div class="small text-gray-500">July 23, 2023</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="mr-3">
                    <div class="icon-circle bg-success">
                        <i class="fas fa-donate text-white"></i>
                    </div>
                </div>
                <div>
                    <div class="small text-gray-500">July 23, 2023</div>
                    $290.29 pending tansaction!
                </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="mr-3">
                    <div class="icon-circle bg-warning">
                        <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                </div>
                <div>
                    <div class="small text-gray-500">July 23, 2023</div>
                    Spending Alert: you have used 85% of your budget.
                </div>
            </a>
            <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
        </div>
    </li>

    <!-- Nav Item - Messages -->
    <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-envelope fa-fw"></i>
            <!-- Counter - Messages -->
            <span class="badge badge-danger badge-counter">6</span>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
            aria-labelledby="messagesDropdown">
            <h6 class="dropdown-header">
                Message Center
            </h6>
            <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src=' {% static "img/undraw_profile_1.svg" %}'
                        alt="...">
                    <div class="status-indicator bg-success"></div>
                </div>
                <div class="font-weight-bold">
                    <div class="text-truncate">Hi there! we have an offer for you that we know you will love.</div>
                    <div class="small text-gray-500">Budget Advisor · 58m</div>
                </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src=' {% static "img/undraw_profile_2.svg" %}'
                        alt="...">
                    <div class="status-indicator"></div>
                </div>
                <div>
                    <div class="text-truncate">Sale alert! One of your favorite stores is having a flash sale.</div>
                    <div class="small text-gray-500">Spending Advisor · 1d</div>
                </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src=' {% static "img/undraw_profile_3.svg" %}'
                        alt="...">
                    <div class="status-indicator bg-warning"></div>
                </div>
                <div>
                    <div class="text-truncate">Last month's report looks great, I am very happy with
                        the progress so far, keep up the good work!</div>
                    <div class="small text-gray-500">Budget Advisor · 2d</div>
                </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                        alt="...">
                    <div class="status-indicator bg-success"></div>
                </div>
                <div>
                    <div class="text-truncate">Check out your proress, go to the dashboard and generate a report today</div>
                    <div class="small text-gray-500">Expense Manager · 2w</div>
                </div>
            </a>
            <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
        </div>
    </li>

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">Dougie Mac</span>
            <img class="img-profile rounded-circle"
                src=' {% static "img/undraw_profile.svg" %}'>
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
            aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Profile
            </a>
            <a class="dropdown-item" href="#">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Settings
            </a>
            <a class="dropdown-item" href="#">
                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                Activity Log
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Logout
            </a>
        </div>
    </li>

</ul>

</nav>
<!-- End of Topbar -->